### ISSUE TITLE
find_* methods unnecessarily slow

### ISSUE THREAD

**Issue by mmjb** [emalgorithm/structured-neural-summarization-replication#1]
Hey,

I had a brief look at your code - it looks quite clean and is nice to read, great job. One observation: In your `find_*` methods, you are iterating over all edges in a given `proto` file, i.e, the cost of that is O(#NumEdges). By doing some prep work and building a dictionary `node_to_outgoing_edges`, you can speed that process up substantially.

**Comment by emalgorithm** [comment]
Good point, thanks a lot, I'll change it as soon as possible!
