### ISSUE TITLE
[minor] Replace SGD eventually

### ISSUE THREAD

**Issue by mallamanis** [emalgorithm/structured-neural-summarization-replication#3]
I see that you are using SGD [here](https://github.com/emalgorithm/structured-neural-summarization-replication/blob/b5b1883e2fbf32c65ac9d5813c6b260811c294cd/models/lstm_to_lstm_full_training.py#L92). This is okay for now, but keep in mind that you might want to test `Adam` in the future, especially if things don't converge as well. Or at least trying to add momentum to SGD.

**Comment by emalgorithm** [comment]
Changed to Adam! Thanks

**Comment by emalgorithm** [comment]
Changed to Adam. Thanks!
